BOX-163 Перенести решения из accesso в cardbox
cardbox/backend pull request #23
Opened 2021-07-19 13:13 UTC by Drevoed

2021-07-19 19:02 UTC, Drevoed reviewed
self-reviewed

2021-07-20 09:53 UTC, sergeysova requested changes

2021-07-20 09:53 UTC, sergeysova commented on api-internal/openapi.yaml
> +  /auth.done:
```suggestion
  /accesso/auth.done:
```

2021-07-20 09:53 UTC, sergeysova commented on api-internal/openapi.yaml
> +  /auth.url:
```suggestion
  /accesso/auth.params:
```

2021-07-20 09:53 UTC, sergeysova commented on api-internal/src/routes/accesso/auth_url.rs
> +    let mut accesso = Url::parse(&config.accesso.url).wrap_err("Could not parse url")?;
Кажется лучше вынести этот Парсинга и валидация на этап инициализации приложения

2021-07-20 09:53 UTC, sergeysova commented on config/default-development.toml
> +redirect_back_url = "https://cardbox.dev/accesso/done"
```suggestion
redirect_back_url = "https://cards.sova.dev/accesso/done"
```

2021-07-20 09:53 UTC, sergeysova commented on config/default-development.toml
> +url = "https://accesso.app"
```suggestion
url = "https://accesso.sova.dev"
```

2021-07-20 09:53 UTC, sergeysova commented on config/default-development.toml
> +redirect_back_url = "https://cardbox.dev/accesso/done"
Мб лучше указать локальный инстанс

2021-07-20 09:53 UTC, sergeysova commented on core/src/contracts/repo/session_token.rs
> +    async fn delete_token_by_user(&self, user_id: Uuid) -> RepoResult<u64>;
```suggestion
    async fn token_delete_by_user(&self, user_id: Uuid) -> RepoResult<u64>;
```

2021-07-20 09:53 UTC, sergeysova commented on core/src/contracts/repo/session_token.rs
> +    async fn delete_token_by_user(&self, user_id: Uuid) -> RepoResult<u64>;
https://gist.github.com/sergeysova/9f6dc24e21efe5f5bb4f9878216c2ce9

2021-07-20 09:53 UTC, sergeysova commented on core/src/contracts/repo/user.rs
> +    async fn find_user_by_accesso(&self, accesso_id: Uuid) -> RepoResult<Option<models::User>> {
```suggestion
    async fn user_find_by_accesso(&self, accesso_id: Uuid) -> RepoResult<Option<models::User>> {
```

2021-07-20 09:53 UTC, sergeysova commented on core/src/contracts/repo/session_token.rs
> +    async fn delete_token_by_user(&self, user_id: Uuid) -> RepoResult<u64>;
token_delete
token_create
token_find_by_user

2021-07-20 10:26 UTC, Drevoed commented on config/default-development.toml
> +redirect_back_url = "https://cardbox.dev/accesso/done"
думаю лучше локальный вообще

2021-07-20 10:38 UTC, Drevoed commented on api-internal/src/routes/accesso/auth_url.rs
> +    let mut accesso = Url::parse(&config.accesso.url).wrap_err("Could not parse url")?;
Тогда будет глобальный мутабельный урл, неудобно работать будет.

2021-07-20 10:55 UTC, Drevoed commented on api-internal/src/routes/accesso/auth_url.rs
> +    let mut accesso = Url::parse(&config.accesso.url).wrap_err("Could not parse url")?;
NVM, fixed

2021-07-20 16:17 UTC, sergeysova approved these changes

2021-07-20 16:19 UTC, merged