Feature/add tables
cardbox/backend pull request #24
Opened 2021-07-19 20:16 UTC by Drevoed

2021-07-19 20:16 UTC, Drevoed commented
![image](https://user-images.githubusercontent.com/53709100/126221581-6ad9a2d4-706f-4840-b6f4-40ab8ddfb278.png)

2021-07-20 09:56 UTC, sergeysova requested changes

2021-07-20 09:56 UTC, sergeysova commented on migrations/20210719191915_create_cards.up.sql
> +    user_id    uuid        NOT NULL REFERENCES users ("id"),
```suggestion
    author_id    uuid        NOT NULL REFERENCES users ("id"),
```

2021-07-20 09:56 UTC, sergeysova commented on migrations/20210719200330_create_socials.up.sql
> +    user_id uuid    NOT NULL REFERENCES users ("id"),
Нужен ли индекс? Или автоматом будет создан?

2021-07-20 16:18 UTC, sergeysova approved these changes

2021-07-20 16:19 UTC, merged