BOX-64
cardbox/backend pull request #27
Opened 2021-07-21 21:15 UTC by Drevoed

2021-07-21 21:24 UTC, Drevoed reviewed
self-reviewed

2021-07-21 21:24 UTC, Drevoed commented on migrations/20210721124150_trgm_extension.down.sql
> +DROP EXTENSION IF EXISTS pg_trgm;
Need to remove this because database user cannot create extensions

2021-07-21 21:24 UTC, Drevoed commented on migrations/20210721124150_trgm_extension.up.sql
> +CREATE EXTENSION IF NOT EXISTS pg_trgm;
Need to remove this because database user cannot create extensions

2021-07-21 21:26 UTC, Drevoed commented on app/src/cards.rs
> +        Ok(search_results.into_iter().unique_by(|c| c.id).collect())
Might actually need to use some kind of search type indication or priority.

But for now let's just search everywhere

2021-07-21 22:26 UTC, sergeysova requested changes

2021-07-21 22:26 UTC, sergeysova commented on api-internal/openapi.yaml
> +                search:
```suggestion
                query:
```

2021-07-21 22:26 UTC, sergeysova commented on api-internal/openapi.yaml
> +                      $ref: '#/components/schemas/Card'
Я бы ещё возвращал список авторов карточек, отдельно users.
Чтобы можно было отображать карточку зная автора

2021-07-21 22:26 UTC, sergeysova commented on api-internal/openapi.yaml
> +        401:
```suggestion
        400:
```

Лучше составить полный список ошибок в формате: https://github.com/atomix-team/codestyle/blob/master/api-conventions.md

2021-07-21 22:26 UTC, sergeysova commented on api-internal/src/routes/cards/search.rs
> +        .card_search(&body.search)
```suggestion
        .cards_search(&body.search)
```

2021-07-21 22:26 UTC, sergeysova commented on app/src/cards.rs
> +            db.cards_find_by_title(search),
Почему не сделать одним запросом￼￼￼￼?

2021-07-21 22:26 UTC, sergeysova commented on app/src/cards.rs
> +        )?;
По хорошему нужно ограничение по количеству выдачи, мб одним запросом и было бы проще. Иначе можем всю базу отдать так

2021-07-21 22:26 UTC, sergeysova commented on db/src/repos/card.rs
> +            WHERE jsonb_to_tsvector('english', jsonb_path_query_array(contents, 'strict $.**.text'), '[
А этот запрос не будет искать в блоках кода в редакторе? Есть ощущение что будет, но ведь не должно быть так

2021-07-22 06:39 UTC, Drevoed commented on db/src/repos/card.rs
> +            WHERE jsonb_to_tsvector('english', jsonb_path_query_array(contents, 'strict $.**.text'), '[
Если текст внутри блока кода в поле text - то будет

2021-07-22 08:37 UTC, Drevoed commented on app/src/cards.rs
> +            db.cards_find_by_title(search),
Потому что пока что ищем по всем и не вижу сейчас смысла закладывать это сейчас в один запрос, все равно потом придётся оптимизировать

2021-07-22 09:08 UTC, Drevoed commented on api-internal/openapi.yaml
> +                      $ref: '#/components/schemas/Card'
Айдишники авторов и так есть в каждой карточке же

2021-07-22 14:21 UTC, sergeysova approved these changes

2021-07-22 14:25 UTC, merged